id: P010556
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:55:50.430238
source_metadata:
  id: bdr:W1KG22580
  title: བོད་རང་སྐྱོང་ལྗོངས་དཔེ་མཛོད་ཁང་གི་གནའ་དཔེའི་དཀར་ཆག
  author: ''
  volumes:
    e8cbf1f8878f4ef3ae42a66f6d1d9c98:
      image_group_id: I1KG22588
      title: ''
      volume_number: 1
      total_pages: 560
      base_file: v001.txt
    2fb5a128aec743d89ad7bdce8442f683:
      image_group_id: I1KG22589
      title: ''
      volume_number: 2
      total_pages: 646
      base_file: v002.txt
    b658a31d414f4ff4ae71d5318bcb16f4:
      image_group_id: I1KG22590
      title: ''
      volume_number: 3
      total_pages: 560
      base_file: v003.txt
    1d0469f03b2d4716aaafa5dd77021b9c:
      image_group_id: I1KG22591
      title: ''
      volume_number: 4
      total_pages: 440
      base_file: v004.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
