id: IA1AED6B3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T13:44:21+00:00'
last_modified: '2022-06-08T14:28:07.117962+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22580
  title: བོད་རང་སྐྱོང་ལྗོངས་དཔེ་མཛོད་ཁང་གི་གནའ་དཔེའི་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    84D8:
      image_group_id: I1KG22588
      title: ''
      total_pages: 560
      order: 1
      base_file: 84D8.txt
    760A:
      image_group_id: I1KG22589
      title: ''
      total_pages: 646
      order: 2
      base_file: 760A.txt
    B6CD:
      image_group_id: I1KG22590
      title: ''
      total_pages: 560
      order: 3
      base_file: B6CD.txt
    7A77:
      image_group_id: I1KG22591
      title: ''
      total_pages: 440
      order: 4
      base_file: 7A77.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
