id: IA1AED6B3
legacy_id: P010556
ocr_import_info:
  bdrc_scan_id: W1KG22580
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T13:41:12'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T13:14:46.023932+00:00'
last_modified: 2022-08-31 21:16:20.804902
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG22580
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG22580
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བོད་རང་སྐྱོང་ལྗོངས་དཔེ་མཛོད་ཁང་གི་གནའ་དཔེའི་དཀར་ཆག
statistics:
  ocr_word_mean_confidence_index: 0.6599199014257883
  ocr_word_median_confidence_index: 0.8500000238418579
quality: null
bases:
  I1KG22591:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22591
      total_pages: 440
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG22591.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.621233649283659
    legacy_id: v004
  I1KG22588:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22588
      total_pages: 560
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22588.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.7144000243105001
    legacy_id: v001
  I1KG22589:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22589
      total_pages: 646
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG22589.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.6809595083346862
    legacy_id: v002
  I1KG22590:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22590
      total_pages: 560
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG22590.txt
    statistics:
      ocr_word_median_confidence_index: 0.7400000095367432
      ocr_word_mean_confidence_index: 0.6294117806564969
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
